### ISSUE TITLE
Intelij in .gitignore 

### ISSUE THREAD

**Issue by phaynes** [NationalSecurityAgency/MADCert#5]
Hi,

I can see in your .gitignore 
# IntelliJ IDEA files
.idea/
*.iml

Below is the link to the Russian development lab for InteliJ
https://www.jetbrains.com/careers/jobs/senior-software-developer-13/

Eclipse / Visual Studio provide excellent alternative dev environments.

Kind Regards

**Comment by ctubbsii** [comment]
Closing as off-topic for this repository. IDE developer preferences are not relevant technical topics for this open source project.

**Comment by phaynes** [comment]
Dear Chris, 

Within the secure environments I work, choice of Developer IDE is restricted and a sensitive issue.  Removal of references to certain IDE's simply makes it easier to trust the source of techology - hence my suggestion that it is not off topic.

Kind Regards,
Philip
